# These are supported funding model platforms

github: [ramadis] # Replace with your GitHub username if needed
patreon: # Replace with your Patreon username if needed
open_collective: # Replace with your Open Collective username if needed
ko_fi: # Replace with your Ko-fi username if needed
tidelift: # Replace with a tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a community bridge project name e.g., cloud-foundry
liberapay: # Replace with your Liberapay username if needed
issuehunt: # Replace with your IssueHunt username if needed
otechie: # Replace with your Otechie username if needed
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
