blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/ramadis/vibe-class/discussions
    about: Please ask and answer questions here
  - name: GitHub Community Support
    url: https://github.community/
    about: Ask general GitHub-related questions
